export const getAlphabet = () => {
    let data =
    {
        A:
            [{ name: 'Afghanistan', code: '+93' },
            { name: 'Aland Islands', code: '+358' },
            { name: 'Albania', code: '+355' },
            { name: 'Algeria', code: '+213' },
            { name: 'AmericanSamoa', code: '+1684' },
            { name: 'Andorra', code: '+376' },
            { name: 'Angola', code: '+244' },
            { name: 'Anguilla', code: '+1264' },
            { name: 'Antarctica', code: '+672' },
            { name: 'Antigua and Barbuda', code: '+1268' },
            { name: 'Argentina', code: '+54' },
            { name: 'Armenia', code: '+374' },
            { name: 'Aruba', code: '+297' },
            { name: 'Australia', code: '+61' },
            { name: 'Austria', code: '+43' },
            { name: 'Azerbaijan', code: '+994' }],
        B:
            [{ name: 'Bahamas', code: '+1242' },
            { name: 'Bahrain', code: '+973' },
            { name: 'Bangladesh', code: '+880' },
            { name: 'Barbados', code: '+1246' },
            { name: 'Belarus', code: '+375' },
            { name: 'Belgium', code: '+32' },
            { name: 'Belize', code: '+501' },
            { name: 'Benin', code: '+229' },
            { name: 'Bermuda', code: '+1441' },
            { name: 'Bhutan', code: '+975' },
            { name: 'Bolivia, Plurinational State of', code: '+591' },
            { name: 'Bosnia and Herzegovina', code: '+387' },
            { name: 'Botswana', code: '+267' },
            { name: 'Brazil', code: '+55' },
            { name: 'British Indian Ocean Territory', code: '+246' },
            { name: 'Brunei Darussalam', code: '+673' },
            { name: 'Bulgaria', code: '+359' },
            { name: 'Burkina Faso', code: '+226' },
            { name: 'Burundi', code: '+257' }],
        C:
            [{ name: 'Cambodia', code: '+855' },
            { name: 'Cameroon', code: '+237' },
            { name: 'Canada', code: '+1' },
            { name: 'Cape Verde', code: '+238' },
            { name: 'Cayman Islands', code: '+ 345' },
            { name: 'Central African Republic', code: '+236' },
            { name: 'Chad', code: '+235' },
            { name: 'Chile', code: '+56' },
            { name: 'China', code: '+86' },
            { name: 'Christmas Island', code: '+61' },
            { name: 'Cocos (Keeling) Islands', code: '+61' },
            { name: 'Colombia', code: '+57' },
            { name: 'Comoros', code: '+269' },
            { name: 'Congo', code: '+242' },
            {
                name: 'Congo, The Democratic Republic of the Congo',
                code: '+243'
            },
            { name: 'Cook Islands', code: '+682' },
            { name: 'Costa Rica', code: '+506' },
            { name: 'Cote d\'Ivoire', code: '+225' },
            { name: 'Croatia', code: '+385' },
            { name: 'Cuba', code: '+53' },
            { name: 'Cyprus', code: '+357' },
            { name: 'Czech Republic', code: '+420' }],
        D:
            [{ name: 'Denmark', code: '+45' },
            { name: 'Djibouti', code: '+253' },
            { name: 'Dominica', code: '+1767' },
            { name: 'Dominican Republic', code: '+1849' }],
        E:
            [{ name: 'Ecuador', code: '+593' },
            { name: 'Egypt', code: '+20' },
            { name: 'El Salvador', code: '+503' },
            { name: 'Equatorial Guinea', code: '+240' },
            { name: 'Eritrea', code: '+291' },
            { name: 'Estonia', code: '+372' },
            { name: 'Ethiopia', code: '+251' }],
        F:
            [{ name: 'Falkland Islands (Malvinas)', code: '+500' },
            { name: 'Faroe Islands', code: '+298' },
            { name: 'Fiji', code: '+679' },
            { name: 'Finland', code: '+358' },
            { name: 'France', code: '+33' },
            { name: 'French Guiana', code: '+594' },
            { name: 'French Polynesia', code: '+689' }],
        G:
            [{ name: 'Gabon', code: '+241' },
            { name: 'Gambia', code: '+220' },
            { name: 'Georgia', code: '+995' },
            { name: 'Germany', code: '+49' },
            { name: 'Ghana', code: '+233' },
            { name: 'Gibraltar', code: '+350' },
            { name: 'Greece', code: '+30' },
            { name: 'Greenland', code: '+299' },
            { name: 'Grenada', code: '+1473' },
            { name: 'Guadeloupe', code: '+590' },
            { name: 'Guam', code: '+1671' },
            { name: 'Guatemala', code: '+502' },
            { name: 'Guernsey', code: '+44' },
            { name: 'Guinea', code: '+224' },
            { name: 'Guinea-Bissau', code: '+245' },
            { name: 'Guyana', code: '+595' }],
        H:
            [{ name: 'Haiti', code: '+509' },
            { name: 'Holy See (Vatican City State)', code: '+379' },
            { name: 'Honduras', code: '+504' },
            { name: 'Hong Kong', code: '+852' },
            { name: 'Hungary', code: '+36' }],
        I:
            [{ name: 'Iceland', code: '+354' },
            { name: 'India', code: '+91' },
            { name: 'Indonesia', code: '+62' },
            { name: 'Iran, Islamic Republic of Persian Gulf', code: '+98' },
            { name: 'Iraq', code: '+964' },
            { name: 'Ireland', code: '+353' },
            { name: 'Isle of Man', code: '+44' },
            { name: 'Israel', code: '+972' },
            { name: 'Italy', code: '+39' }],
        J:
            [{ name: 'Jamaica', code: '+1876' },
            { name: 'Japan', code: '+81' },
            { name: 'Jersey', code: '+44' },
            { name: 'Jordan', code: '+962' }],
        K:
            [{ name: 'Kazakhstan', code: '+77' },
            { name: 'Kenya', code: '+254' },
            { name: 'Kiribati', code: '+686' },
            {
                name: 'Korea, Democratic People\'s Republic of Korea',
                code: '+850'
            },
            { name: 'Korea, Republic of South Korea', code: '+82' },
            { name: 'Kuwait', code: '+965' },
            { name: 'Kyrgyzstan', code: '+996' }],
        L:
            [{ name: 'Laos', code: '+856' },
            { name: 'Latvia', code: '+371' },
            { name: 'Lebanon', code: '+961' },
            { name: 'Lesotho', code: '+266' },
            { name: 'Liberia', code: '+231' },
            { name: 'Libyan Arab Jamahiriya', code: '+218' },
            { name: 'Liechtenstein', code: '+423' },
            { name: 'Lithuania', code: '+370' },
            { name: 'Luxembourg', code: '+352' }],
        M:
            [{ name: 'Macao', code: '+853' },
            { name: 'Macedonia', code: '+389' },
            { name: 'Madagascar', code: '+261' },
            { name: 'Malawi', code: '+265' },
            { name: 'Malaysia', code: '+60' },
            { name: 'Maldives', code: '+960' },
            { name: 'Mali', code: '+223' },
            { name: 'Malta', code: '+356' },
            { name: 'Marshall Islands', code: '+692' },
            { name: 'Martinique', code: '+596' },
            { name: 'Mauritania', code: '+222' },
            { name: 'Mauritius', code: '+230' },
            { name: 'Mayotte', code: '+262' },
            { name: 'Mexico', code: '+52' },
            {
                name: 'Micronesia, Federated States of Micronesia',
                code: '+691'
            },
            { name: 'Moldova', code: '+373' },
            { name: 'Monaco', code: '+377' },
            { name: 'Mongolia', code: '+976' },
            { name: 'Montenegro', code: '+382' },
            { name: 'Montserrat', code: '+1664' },
            { name: 'Morocco', code: '+212' },
            { name: 'Mozambique', code: '+258' },
            { name: 'Myanmar', code: '+95' }],
        N:
            [{ name: 'Namibia', code: '+264' },
            { name: 'Nauru', code: '+674' },
            { name: 'Nepal', code: '+977' },
            { name: 'Netherlands', code: '+31' },
            { name: 'Netherlands Antilles', code: '+599' },
            { name: 'New Caledonia', code: '+687' },
            { name: 'New Zealand', code: '+64' },
            { name: 'Nicaragua', code: '+505' },
            { name: 'Niger', code: '+227' },
            { name: 'Nigeria', code: '+234' },
            { name: 'Niue', code: '+683' },
            { name: 'Norfolk Island', code: '+672' },
            { name: 'Northern Mariana Islands', code: '+1670' },
            { name: 'Norway', code: '+47' }],
        O: [{ name: 'Oman', code: '+968' }],
        P:
            [{ name: 'Pakistan', code: '+92' },
            { name: 'Palau', code: '+680' },
            { name: 'Palestinian Territory, Occupied', code: '+970' },
            { name: 'Panama', code: '+507' },
            { name: 'Papua New Guinea', code: '+675' },
            { name: 'Paraguay', code: '+595' },
            { name: 'Peru', code: '+51' },
            { name: 'Philippines', code: '+63' },
            { name: 'Pitcairn', code: '+872' },
            { name: 'Poland', code: '+48' },
            { name: 'Portugal', code: '+351' },
            { name: 'Puerto Rico', code: '+1939' }],
        Q: [{ name: 'Qatar', code: '+974' }],
        R:
            [{ name: 'Romania', code: '+40' },
            { name: 'Russia', code: '+7' },
            { name: 'Rwanda', code: '+250' },
            { name: 'Reunion', code: '+262' }],
        S:
            [{ name: 'Saint Barthelemy', code: '+590' },
            {
                name: 'Saint Helena, Ascension and Tristan Da Cunha',
                code: '+290'
            },
            { name: 'Saint Kitts and Nevis', code: '+1869' },
            { name: 'Saint Lucia', code: '+1758' },
            { name: 'Saint Martin', code: '+590' },
            { name: 'Saint Pierre and Miquelon', code: '+508' },
            { name: 'Saint Vincent and the Grenadines', code: '+1784' },
            { name: 'Samoa', code: '+685' },
            { name: 'San Marino', code: '+378' },
            { name: 'Sao Tome and Principe', code: '+239' },
            { name: 'Saudi Arabia', code: '+966' },
            { name: 'Senegal', code: '+221' },
            { name: 'Serbia', code: '+381' },
            { name: 'Seychelles', code: '+248' },
            { name: 'Sierra Leone', code: '+232' },
            { name: 'Singapore', code: '+65' },
            { name: 'Slovakia', code: '+421' },
            { name: 'Slovenia', code: '+386' },
            { name: 'Solomon Islands', code: '+677' },
            { name: 'Somalia', code: '+252' },
            { name: 'South Africa', code: '+27' },
            { name: 'South Sudan', code: '+211' },
            {
                name: 'South Georgia and the South Sandwich Islands',
                code: '+500'
            },
            { name: 'Spain', code: '+34' },
            { name: 'Sri Lanka', code: '+94' },
            { name: 'Sudan', code: '+249' },
            { name: 'Suriname', code: '+597' },
            { name: 'Svalbard and Jan Mayen', code: '+47' },
            { name: 'Swaziland', code: '+268' },
            { name: 'Sweden', code: '+46' },
            { name: 'Switzerland', code: '+41' },
            { name: 'Syrian Arab Republic', code: '+963' }],
        T:
            [{ name: 'Taiwan', code: '+886' },
            { name: 'Tajikistan', code: '+992' },
            { name: 'Tanzania, United Republic of Tanzania', code: '+255' },
            { name: 'Thailand', code: '+66' },
            { name: 'Timor-Leste', code: '+670' },
            { name: 'Togo', code: '+228' },
            { name: 'Tokelau', code: '+690' },
            { name: 'Tonga', code: '+676' },
            { name: 'Trinidad and Tobago', code: '+1868' },
            { name: 'Tunisia', code: '+216' },
            { name: 'Turkey', code: '+90' },
            { name: 'Turkmenistan', code: '+993' },
            { name: 'Turks and Caicos Islands', code: '+1649' },
            { name: 'Tuvalu', code: '+688' }],
        U:
            [{ name: 'Uganda', code: '+256' },
            { name: 'Ukraine', code: '+380' },
            { name: 'United Arab Emirates', code: '+971' },
            { name: 'United Kingdom', code: '+44' },
            { name: 'United States', code: '+1' },
            { name: 'Uruguay', code: '+598' },
            { name: 'Uzbekistan', code: '+998' }],
        V:
            [{ name: 'Vanuatu', code: '+678' },
            {
                name: 'Venezuela, Bolivarian Republic of Venezuela',
                code: '+58'
            },
            { name: 'Vietnam', code: '+84' },
            { name: 'Virgin Islands, British', code: '+1284' },
            { name: 'Virgin Islands, U.S.', code: '+1340' }],
        W: [{ name: 'Wallis and Futuna', code: '+681' }],
        Y: [{ name: 'Yemen', code: '+967' }],
        Z:
            [{ name: 'Zambia', code: '+260' },
            { name: 'Zimbabwe', code: '+263' }]
    }
    return data
}

/*
[{ "Code": "AF", "Name": "Afghanistan" }, { "Code": "AX", "Name": "\u00c5land Islands" }, { "Code": "AL", "Name": "Albania" }, { "Code": "DZ", "Name": "Algeria" }, { "Code": "AS", "Name": "American Samoa" }, { "Code": "AD", "Name": "Andorra" }, { "Code": "AO", "Name": "Angola" }, { "Code": "AI", "Name": "Anguilla" }, { "Code": "AQ", "Name": "Antarctica" }, { "Code": "AG", "Name": "Antigua and Barbuda" }, { "Code": "AR", "Name": "Argentina" }, { "Code": "AM", "Name": "Armenia" }, { "Code": "AW", "Name": "Aruba" }, { "Code": "AU", "Name": "Australia" }, { "Code": "AT", "Name": "Austria" }, { "Code": "AZ", "Name": "Azerbaijan" }, { "Code": "BS", "Name": "Bahamas" }, { "Code": "BH", "Name": "Bahrain" }, { "Code": "BD", "Name": "Bangladesh" }, { "Code": "BB", "Name": "Barbados" }, { "Code": "BY", "Name": "Belarus" }, { "Code": "BE", "Name": "Belgium" }, { "Code": "BZ", "Name": "Belize" }, { "Code": "BJ", "Name": "Benin" }, { "Code": "BM", "Name": "Bermuda" }, { "Code": "BT", "Name": "Bhutan" }, { "Code": "BO", "Name": "Bolivia, Plurinational State of" }, { "Code": "BQ", "Name": "Bonaire, Sint Eustatius and Saba" }, { "Code": "BA", "Name": "Bosnia and Herzegovina" }, { "Code": "BW", "Name": "Botswana" }, { "Code": "BV", "Name": "Bouvet Island" }, { "Code": "BR", "Name": "Brazil" }, { "Code": "IO", "Name": "British Indian Ocean Territory" }, { "Code": "BN", "Name": "Brunei Darussalam" }, { "Code": "BG", "Name": "Bulgaria" }, { "Code": "BF", "Name": "Burkina Faso" }, { "Code": "BI", "Name": "Burundi" }, { "Code": "KH", "Name": "Cambodia" }, { "Code": "CM", "Name": "Cameroon" }, { "Code": "CA", "Name": "Canada" }, { "Code": "CV", "Name": "Cape Verde" }, { "Code": "KY", "Name": "Cayman Islands" }, { "Code": "CF", "Name": "Central African Republic" }, { "Code": "TD", "Name": "Chad" }, { "Code": "CL", "Name": "Chile" }, { "Code": "CN", "Name": "China" }, { "Code": "CX", "Name": "Christmas Island" }, { "Code": "CC", "Name": "Cocos (Keeling) Islands" }, { "Code": "CO", "Name": "Colombia" }, { "Code": "KM", "Name": "Comoros" }, { "Code": "CG", "Name": "Congo" }, { "Code": "CD", "Name": "Congo, the Democratic Republic of the" }, { "Code": "CK", "Name": "Cook Islands" }, { "Code": "CR", "Name": "Costa Rica" }, { "Code": "CI", "Name": "C\u00f4te d'Ivoire" }, { "Code": "HR", "Name": "Croatia" }, { "Code": "CU", "Name": "Cuba" }, { "Code": "CW", "Name": "Cura\u00e7ao" }, { "Code": "CY", "Name": "Cyprus" }, { "Code": "CZ", "Name": "Czech Republic" }, { "Code": "DK", "Name": "Denmark" }, { "Code": "DJ", "Name": "Djibouti" }, { "Code": "DM", "Name": "Dominica" }, { "Code": "DO", "Name": "Dominican Republic" }, { "Code": "EC", "Name": "Ecuador" }, { "Code": "EG", "Name": "Egypt" }, { "Code": "SV", "Name": "El Salvador" }, { "Code": "GQ", "Name": "Equatorial Guinea" }, { "Code": "ER", "Name": "Eritrea" }, { "Code": "EE", "Name": "Estonia" }, { "Code": "ET", "Name": "Ethiopia" }, { "Code": "FK", "Name": "Falkland Islands (Malvinas)" }, { "Code": "FO", "Name": "Faroe Islands" }, { "Code": "FJ", "Name": "Fiji" }, { "Code": "FI", "Name": "Finland" }, { "Code": "FR", "Name": "France" }, { "Code": "GF", "Name": "French Guiana" }, { "Code": "PF", "Name": "French Polynesia" }, { "Code": "TF", "Name": "French Southern Territories" }, { "Code": "GA", "Name": "Gabon" }, { "Code": "GM", "Name": "Gambia" }, { "Code": "GE", "Name": "Georgia" }, { "Code": "DE", "Name": "Germany" }, { "Code": "GH", "Name": "Ghana" }, { "Code": "GI", "Name": "Gibraltar" }, { "Code": "GR", "Name": "Greece" }, { "Code": "GL", "Name": "Greenland" }, { "Code": "GD", "Name": "Grenada" }, { "Code": "GP", "Name": "Guadeloupe" }, { "Code": "GU", "Name": "Guam" }, { "Code": "GT", "Name": "Guatemala" }, { "Code": "GG", "Name": "Guernsey" }, { "Code": "GN", "Name": "Guinea" }, { "Code": "GW", "Name": "Guinea-Bissau" }, { "Code": "GY", "Name": "Guyana" }, { "Code": "HT", "Name": "Haiti" }, { "Code": "HM", "Name": "Heard Island and McDonald Islands" }, { "Code": "VA", "Name": "Holy See (Vatican City State)" }, { "Code": "HN", "Name": "Honduras" }, { "Code": "HK", "Name": "Hong Kong" }, { "Code": "HU", "Name": "Hungary" }, { "Code": "IS", "Name": "Iceland" }, { "Code": "IN", "Name": "India" }, { "Code": "ID", "Name": "Indonesia" }, { "Code": "IR", "Name": "Iran, Islamic Republic of" }, { "Code": "IQ", "Name": "Iraq" }, { "Code": "IE", "Name": "Ireland" }, { "Code": "IM", "Name": "Isle of Man" }, { "Code": "IL", "Name": "Israel" }, { "Code": "IT", "Name": "Italy" }, { "Code": "JM", "Name": "Jamaica" }, { "Code": "JP", "Name": "Japan" }, { "Code": "JE", "Name": "Jersey" }, { "Code": "JO", "Name": "Jordan" }, { "Code": "KZ", "Name": "Kazakhstan" }, { "Code": "KE", "Name": "Kenya" }, { "Code": "KI", "Name": "Kiribati" }, { "Code": "KP", "Name": "Korea, Democratic People's Republic of" }, { "Code": "KR", "Name": "Korea, Republic of" }, { "Code": "KW", "Name": "Kuwait" }, { "Code": "KG", "Name": "Kyrgyzstan" }, { "Code": "LA", "Name": "Lao People's Democratic Republic" }, { "Code": "LV", "Name": "Latvia" }, { "Code": "LB", "Name": "Lebanon" }, { "Code": "LS", "Name": "Lesotho" }, { "Code": "LR", "Name": "Liberia" }, { "Code": "LY", "Name": "Libya" }, { "Code": "LI", "Name": "Liechtenstein" }, { "Code": "LT", "Name": "Lithuania" }, { "Code": "LU", "Name": "Luxembourg" }, { "Code": "MO", "Name": "Macao" }, { "Code": "MK", "Name": "Macedonia, the Former Yugoslav Republic of" }, { "Code": "MG", "Name": "Madagascar" }, { "Code": "MW", "Name": "Malawi" }, { "Code": "MY", "Name": "Malaysia" }, { "Code": "MV", "Name": "Maldives" }, { "Code": "ML", "Name": "Mali" }, { "Code": "MT", "Name": "Malta" }, { "Code": "MH", "Name": "Marshall Islands" }, { "Code": "MQ", "Name": "Martinique" }, { "Code": "MR", "Name": "Mauritania" }, { "Code": "MU", "Name": "Mauritius" }, { "Code": "YT", "Name": "Mayotte" }, { "Code": "MX", "Name": "Mexico" }, { "Code": "FM", "Name": "Micronesia, Federated States of" }, { "Code": "MD", "Name": "Moldova, Republic of" }, { "Code": "MC", "Name": "Monaco" }, { "Code": "MN", "Name": "Mongolia" }, { "Code": "ME", "Name": "Montenegro" }, { "Code": "MS", "Name": "Montserrat" }, { "Code": "MA", "Name": "Morocco" }, { "Code": "MZ", "Name": "Mozambique" }, { "Code": "MM", "Name": "Myanmar" }, { "Code": "NA", "Name": "Namibia" }, { "Code": "NR", "Name": "Nauru" }, { "Code": "NP", "Name": "Nepal" }, { "Code": "NL", "Name": "Netherlands" }, { "Code": "NC", "Name": "New Caledonia" }, { "Code": "NZ", "Name": "New Zealand" }, { "Code": "NI", "Name": "Nicaragua" }, { "Code": "NE", "Name": "Niger" }, { "Code": "NG", "Name": "Nigeria" }, { "Code": "NU", "Name": "Niue" }, { "Code": "NF", "Name": "Norfolk Island" }, { "Code": "MP", "Name": "Northern Mariana Islands" }, { "Code": "NO", "Name": "Norway" }, { "Code": "OM", "Name": "Oman" }, { "Code": "PK", "Name": "Pakistan" }, { "Code": "PW", "Name": "Palau" }, { "Code": "PS", "Name": "Palestine, State of" }, { "Code": "PA", "Name": "Panama" }, { "Code": "PG", "Name": "Papua New Guinea" }, { "Code": "PY", "Name": "Paraguay" }, { "Code": "PE", "Name": "Peru" }, { "Code": "PH", "Name": "Philippines" }, { "Code": "PN", "Name": "Pitcairn" }, { "Code": "PL", "Name": "Poland" }, { "Code": "PT", "Name": "Portugal" }, { "Code": "PR", "Name": "Puerto Rico" }, { "Code": "QA", "Name": "Qatar" }, { "Code": "RE", "Name": "R\u00e9union" }, { "Code": "RO", "Name": "Romania" }, { "Code": "RU", "Name": "Russian Federation" }, { "Code": "RW", "Name": "Rwanda" }, { "Code": "BL", "Name": "Saint Barth\u00e9lemy" }, { "Code": "SH", "Name": "Saint Helena, Ascension and Tristan da Cunha" }, { "Code": "KN", "Name": "Saint Kitts and Nevis" }, { "Code": "LC", "Name": "Saint Lucia" }, { "Code": "MF", "Name": "Saint Martin (French part)" }, { "Code": "PM", "Name": "Saint Pierre and Miquelon" }, { "Code": "VC", "Name": "Saint Vincent and the Grenadines" }, { "Code": "WS", "Name": "Samoa" }, { "Code": "SM", "Name": "San Marino" }, { "Code": "ST", "Name": "Sao Tome and Principe" }, { "Code": "SA", "Name": "Saudi Arabia" }, { "Code": "SN", "Name": "Senegal" }, { "Code": "RS", "Name": "Serbia" }, { "Code": "SC", "Name": "Seychelles" }, { "Code": "SL", "Name": "Sierra Leone" }, { "Code": "SG", "Name": "Singapore" }, { "Code": "SX", "Name": "Sint Maarten (Dutch part)" }, { "Code": "SK", "Name": "Slovakia" }, { "Code": "SI", "Name": "Slovenia" }, { "Code": "SB", "Name": "Solomon Islands" }, { "Code": "SO", "Name": "Somalia" }, { "Code": "ZA", "Name": "South Africa" }, { "Code": "GS", "Name": "South Georgia and the South Sandwich Islands" }, { "Code": "SS", "Name": "South Sudan" }, { "Code": "ES", "Name": "Spain" }, { "Code": "LK", "Name": "Sri Lanka" }, { "Code": "SD", "Name": "Sudan" }, { "Code": "SR", "Name": "Suriname" }, { "Code": "SJ", "Name": "Svalbard and Jan Mayen" }, { "Code": "SZ", "Name": "Swaziland" }, { "Code": "SE", "Name": "Sweden" }, { "Code": "CH", "Name": "Switzerland" }, { "Code": "SY", "Name": "Syrian Arab Republic" }, { "Code": "TW", "Name": "Taiwan, Province of China" }, { "Code": "TJ", "Name": "Tajikistan" }, { "Code": "TZ", "Name": "Tanzania, United Republic of" }, { "Code": "TH", "Name": "Thailand" }, { "Code": "TL", "Name": "Timor-Leste" }, { "Code": "TG", "Name": "Togo" }, { "Code": "TK", "Name": "Tokelau" }, { "Code": "TO", "Name": "Tonga" }, { "Code": "TT", "Name": "Trinidad and Tobago" }, { "Code": "TN", "Name": "Tunisia" }, { "Code": "TR", "Name": "Turkey" }, { "Code": "TM", "Name": "Turkmenistan" }, { "Code": "TC", "Name": "Turks and Caicos Islands" }, { "Code": "TV", "Name": "Tuvalu" }, { "Code": "UG", "Name": "Uganda" }, { "Code": "UA", "Name": "Ukraine" }, { "Code": "AE", "Name": "United Arab Emirates" }, { "Code": "GB", "Name": "United Kingdom" }, { "Code": "US", "Name": "United States" }, { "Code": "UM", "Name": "United States Minor Outlying Islands" }, { "Code": "UY", "Name": "Uruguay" }, { "Code": "UZ", "Name": "Uzbekistan" }, { "Code": "VU", "Name": "Vanuatu" }, { "Code": "VE", "Name": "Venezuela, Bolivarian Republic of" }, { "Code": "VN", "Name": "Viet Nam" }, { "Code": "VG", "Name": "Virgin Islands, British" }, { "Code": "VI", "Name": "Virgin Islands, U.S." }, { "Code": "WF", "Name": "Wallis and Futuna" }, { "Code": "EH", "Name": "Western Sahara" }, { "Code": "YE", "Name": "Yemen" }, { "Code": "ZM", "Name": "Zambia" }, { "Code": "ZW", "Name": "Zimbabwe" }]
*/
